In [2]:
import numpy as np

### 1.8 slicing

###### 1.8.1 a[처음값 : 끝값 : 중간값]
- 1차원 뿐만 아니라 다차원 슬라이싱 가능

###### 1.8.2 1차원 슬라이싱

In [2]:
x=np.arange(20)
print(x)
print(x[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]


###### 1.8.3 2차원 슬라이싱

In [3]:
x=np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


###### 1.8.4 3차원 슬라이싱

In [4]:
x=np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5, 1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


### 1.9 indexing & boolean indexing

In [5]:
 a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


###### 1.9.1 다차원 리스트 접근

In [6]:
a[1][1]

6

In [7]:
a[1,1]

6

###### 1.9.2 한번에 여러값 인덱싱

In [8]:
a[[1,1],[1,2]]

array([6, 7])

###### 1.9.3 indexing에 비교, 논리연산자 사용가능
- ! : not
- & : and
- | : or

In [9]:
print(a > 3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [10]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
a[a==1] 

array([1])

In [12]:
a[~(a==1)]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
print(a[(a > 3) |(a < 9)])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### 1.10 random

###### 1.10.1 난수가 들어있는 다양한 형태의 데이터

In [14]:
np.random.rand(5,5)

array([[0.79566899, 0.51586447, 0.25810389, 0.4380893 , 0.21770197],
       [0.96387572, 0.29586525, 0.28047169, 0.25171483, 0.63259634],
       [0.93127508, 0.46747057, 0.08416069, 0.6489414 , 0.12555579],
       [0.39250085, 0.02678021, 0.44251303, 0.31791417, 0.33278778],
       [0.87283362, 0.18893023, 0.2609877 , 0.9288468 , 0.00234829]])

###### 1.10.2 정수 난수

In [15]:
np.random.randint(1,10)

8

###### 1.10.3 정수형 들어가있는 다양한 형태의 데이터

In [16]:
np.random.randint(1, 10, size=(5))

array([1, 2, 6, 1, 9])

In [17]:
np.random.randint(1, 10, size=(5,5))

array([[4, 4, 6, 7, 8],
       [2, 7, 1, 5, 6],
       [8, 5, 4, 6, 4],
       [4, 4, 2, 1, 8],
       [2, 8, 1, 9, 2]])

###### 1.10.4 주어진 리스트 안에  있는 숫자 뽑기

In [18]:
np.random.choice(100, size=(3,4))

array([[67,  8, 43, 43],
       [25, 66, 37, 28],
       [17, 86, 26, 46]])

In [19]:
x= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.random.choice(x, size=(2,2))

array([[6, 9],
       [9, 2]])

In [20]:
import random
random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9])

7

### 1.11 특별한 형태의 행렬

###### 1.11.1 1이 들어가 있는 배열

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###### 1.11.2 0이 들어가 있는 배열

In [22]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

###### 1.11.3 단위 행렬 (행렬곱을 했을 때 자기자신이 나오는)

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###### 1.11.4 행렬 펼치기 (행기준)

In [24]:
x = np.random.randint(1,10,size=(5,5))
x

array([[3, 3, 9, 9, 1],
       [2, 1, 6, 5, 3],
       [4, 5, 9, 6, 9],
       [7, 3, 4, 8, 5],
       [6, 1, 8, 4, 6]])

In [25]:
x.ravel()

array([3, 3, 9, 9, 1, 2, 1, 6, 5, 3, 4, 5, 9, 6, 9, 7, 3, 4, 8, 5, 6, 1,
       8, 4, 6])

In [26]:
x.ravel(order='C')

array([3, 3, 9, 9, 1, 2, 1, 6, 5, 3, 4, 5, 9, 6, 9, 7, 3, 4, 8, 5, 6, 1,
       8, 4, 6])

###### 1.11.5 열기준으로 펼치기

In [27]:
x.ravel(order='F')

array([3, 2, 4, 7, 6, 3, 1, 5, 3, 1, 9, 6, 9, 4, 8, 9, 5, 6, 8, 4, 1, 3,
       9, 5, 6])

###### 1.11.6 flatten : ravel과 동일하나 복사본 반환

In [28]:
x.flatten()

array([3, 3, 9, 9, 1, 2, 1, 6, 5, 3, 4, 5, 9, 6, 9, 7, 3, 4, 8, 5, 6, 1,
       8, 4, 6])

In [29]:
x.flatten(order='F')

array([3, 2, 4, 7, 6, 3, 1, 5, 3, 1, 9, 6, 9, 4, 8, 9, 5, 6, 8, 4, 1, 3,
       9, 5, 6])

In [30]:
temp = x.ravel()
print(temp)

[3 3 9 9 1 2 1 6 5 3 4 5 9 6 9 7 3 4 8 5 6 1 8 4 6]


In [31]:
temp[0] = 100
print("x:\n", x)
print("\ntemp: \n", temp)

x:
 [[100   3   9   9   1]
 [  2   1   6   5   3]
 [  4   5   9   6   9]
 [  7   3   4   8   5]
 [  6   1   8   4   6]]

temp: 
 [100   3   9   9   1   2   1   6   5   3   4   5   9   6   9   7   3   4
   8   5   6   1   8   4   6]


In [32]:
x[0] = 6
x

array([[6, 6, 6, 6, 6],
       [2, 1, 6, 5, 3],
       [4, 5, 9, 6, 9],
       [7, 3, 4, 8, 5],
       [6, 1, 8, 4, 6]])

In [33]:
temp = x.flatten()
temp[0] = 100
print("x:\n", x)
print("\ntemp: \n", temp)

x:
 [[6 6 6 6 6]
 [2 1 6 5 3]
 [4 5 9 6 9]
 [7 3 4 8 5]
 [6 1 8 4 6]]

temp: 
 [100   6   6   6   6   2   1   6   5   3   4   5   9   6   9   7   3   4
   8   5   6   1   8   4   6]


### 1.12 concatenate

In [34]:
x = np.arange(1,4)
y = np.arange(4,7)
print(x)
print(y)

[1 2 3]
[4 5 6]


In [35]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10,20).reshape(2, 5)
print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


###### 1.12.1 배열을 연결

In [36]:
np.concatenate([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

###### 1.12.2 열을 기준으로 

In [37]:
np.concatenate([x,y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

### 1.13 split

###### 1.13.1 배열을 분해

In [38]:
x = np.arange(12)
print(x)
np.split(x,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [39]:
x = np.arange(16).reshape(4,4)
print(x)
np.split(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

###### 1.13.2 열을 기준으로 

In [40]:
x=np.arange(16).reshape(4,4)
print(x)
np.split(x, 2, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### 1.14 broadcast
- 1.14.1 형태(차원)가 다른 행렬끼리의 계산 

###### 1.14.1 다차원 + 숫자 
- 뒤 차원부터 비교해서 shape이 같거나, 차원 중 값이 1인 것이 존재할 때

In [41]:
x = np.array([1, 2, 3])
print(x)
x+1

[1 2 3]


array([2, 3, 4])

###### 1.14.2 2차원 + 1차원

In [3]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,4)
print(x.shape)
print(y.shape)
print(x)
print(y)

(3, 3)
(3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [43]:
x+y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

###### 1.14.3 3차원 + 1차원

In [44]:
a = np.array([10, 20, 30]).reshape(3,1)
b = np.arange(1,4)
print(a.shape)
print(b.shape)

(3, 1)
(3,)


In [45]:
a+b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

- 중간 정리

In [46]:
a = np.arange(12).reshape(4,-1)
b = np.arange(100,103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print(a)
print(b)
print(c)
print(d)

(4, 3)
(3,)
(4,)
(1, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [47]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [48]:
a+c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [49]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

### 1.15 연산 및 집계 함수

In [50]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4).reshape(2, 2)

###### 1.15.1 행렬 곱

In [51]:
x.dot(y)

array([[ 2,  3],
       [ 6, 11]])

###### 1.15.2 전치행렬

In [52]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

###### 1.15.3 역행렬

In [53]:
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

###### 1.15.4 행렬식

In [54]:
np.linalg.det(x)

-2.0

###### 1.15.5 평균, 중앙값, 표준편차, 분산

In [56]:
np.mean(x)

1.5

In [57]:
np.median(x)

1.5

In [58]:
np.std(x)

1.118033988749895

In [59]:
np.var(x)

1.25

###### 1.15.6 합, 합(축변경), 누적합, 누적곱

In [60]:
np.sum(x)

6

In [61]:
np.sum(x, axis=1)

array([1, 5])

In [62]:
np.cumsum(x)

array([0, 1, 3, 6], dtype=int32)

In [63]:
np.cumprod(x)

array([0, 0, 0, 0], dtype=int32)

###### 1.15.7 최소값, 최소값 위치, 최대값 위치

In [64]:
np.min(x)

0

In [65]:
np.argmin(x)

0

In [66]:
np.argmax(x)

3

###### 1.15.8 하나라도 참이어야 참, 모든 요소가 참이어야 참

In [67]:
np.any(x > 4)

False

In [68]:
np.all(x > 4)

False

###### 1.15.9 조건에 맞는 위치 (조건, True 일 경우, False 일 경우)

In [69]:
np.where(x > 4)

(array([], dtype=int64), array([], dtype=int64))

In [70]:
np.where(x > 4, x, -100)

array([[-100, -100],
       [-100, -100]])

### 실습 1
- x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], y = [10, 20, 30, 40, 50, 60, 70, 80 ,90]<br>위의 배열로 Numpy를 사용하여 3X3 행렬을 만든 뒤 행렬합과 행렬곱을 구해주세요.

In [71]:
x=[1, 2, 3, 4, 5, 6, 7, 8, 9]
y=[10, 20, 30, 40, 50, 60, 70, 80, 90]

a = np.array(x).reshape(3,3)
b = np.array(y).reshape(3,3)

In [72]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [73]:
a+b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [74]:
a.dot(b)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

### 실습 2
- 1에서 20사이의 균일한 간격으로 30개의 숫자를 만들고 모든 값에 숫자 10을 더해주세요.

In [75]:
a = np.linspace(1, 20, 30)
print(a+10)

[11.         11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
 14.93103448 15.5862069  16.24137931 16.89655172 17.55172414 18.20689655
 18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
 22.79310345 23.44827586 24.10344828 24.75862069 25.4137931  26.06896552
 26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30.        ]


### 실습 3
- 1 ~ 100까지 난수가 들어있는 2X10X10 배열을 만들고<br>50보다 크거나 같은 값은 1, 50보다 작은 값은 2로 변환하고<br> 2번째 배열에 아래와 같이 붉은 색 위치만 뽑아주세요.

In [80]:
x=np.random.randint(1, 101, size=(200)).reshape(2,10,10)
print(x)

[[[ 41  88  53  40   9  96  77  92  80   5]
  [ 44  68  93  42  80  84  12  59  45  68]
  [ 63  93   2  69  33  58  10  32  37  64]
  [ 24  62  61  41  65  95  26  56  28  68]
  [ 56  87  20  15  25   5   2  38  73  54]
  [ 16  94  76  25   7  76  75  41   9  27]
  [ 85   9  46  32  80  37   4  74   4  63]
  [ 76  70  49  62  90  57  11  57  39  71]
  [ 65  56  33  48   3  53  13  15  63  63]
  [ 54  64  80  93  55  55  86  42  34  95]]

 [[ 96  24  53  73   7  51  78  12  46  90]
  [  1  27  83  71  31  50  69  22  60  24]
  [ 76  11  53  92  51   7  99  63  65  81]
  [  2  56  77  36  73  52  41  16  77  57]
  [ 74  32  23  24  93  69  12  24  16 100]
  [ 45  46  41  64  47  59   2  49  48  98]
  [ 66  85  39  48  55  96  67  35  95  61]
  [ 26  75   6  33  41  76  40  74  33  75]
  [ 17  16  78  59   5  69  55  55  32  40]
  [ 90  63  61  50  10  11  40  79   2  72]]]


In [81]:
z= np.where(x < 50, 2, 1)
print(z)

[[[2 1 1 2 2 1 1 1 1 2]
  [2 1 1 2 1 1 2 1 2 1]
  [1 1 2 1 2 1 2 2 2 1]
  [2 1 1 2 1 1 2 1 2 1]
  [1 1 2 2 2 2 2 2 1 1]
  [2 1 1 2 2 1 1 2 2 2]
  [1 2 2 2 1 2 2 1 2 1]
  [1 1 2 1 1 1 2 1 2 1]
  [1 1 2 2 2 1 2 2 1 1]
  [1 1 1 1 1 1 1 2 2 1]]

 [[1 2 1 1 2 1 1 2 2 1]
  [2 2 1 1 2 1 1 2 1 2]
  [1 2 1 1 1 2 1 1 1 1]
  [2 1 1 2 1 1 2 2 1 1]
  [1 2 2 2 1 1 2 2 2 1]
  [2 2 2 1 2 1 2 2 2 1]
  [1 1 2 2 1 1 1 2 1 1]
  [2 1 2 2 2 1 2 1 2 1]
  [2 2 1 1 2 1 1 1 2 2]
  [1 1 1 1 2 2 2 1 2 1]]]


In [82]:
print(z[1][5:,5:])

[[1 2 2 2 1]
 [1 1 2 1 1]
 [1 2 1 2 1]
 [1 1 1 2 2]
 [2 2 1 2 1]]
